# Generated by Django 4.0.6 on 2022-08-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caneca_id', models.CharField(max_length=6)),
                ('sector', models.CharField(max_length=20)),
                ('cantidadRecogida', models.IntegerField(default=0)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=45)),
                ('cantidadRecogida', models.IntegerField(default=0)),
            ],
        ),
    ]
