# Generated by Django 4.0.6 on 2022-09-13 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('etiquetado', 'etiquetado'), ('clasificado', 'clasificado')], max_length=45)),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivo', models.CharField(max_length=150)),
                ('etiqueta', models.JSONField()),
                ('caneca', models.CharField(choices=[('Ordinario', 'Ordinario'), ('Papel_Carton', 'Papel_Carton'), ('Plastico', 'Plastico'), ('Vidrio', 'Vidrio'), ('Organicos', 'Organicos'), ('Residuos_Peligrosos', 'Residuos_Peligrosos'), ('Aluminio', 'Aluminio')], max_length=45)),
                ('fecha_etiquetado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_puntos', models.PositiveIntegerField(default=0)),
                ('fecha_puntos', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Canecas',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='puntos',
            name='Usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usuario'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usuario'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usuario'),
        ),
    ]
