# Generated by Django 4.0.6 on 2022-10-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_actividad_etiqueta_puntos_usuario_delete_canecas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiqueta',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Bottle_cap',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Brand',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Capacity',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Damage',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Dirtiness',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Material',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Package_color',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Packaging_type',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Reference',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='caneca',
            field=models.CharField(choices=[('Ordinario', 'Ordinario'), ('Papel_Carton', 'Papel_Carton'), ('Plastico', 'Plastico'), ('Vidrio', 'Vidrio'), ('Organicos', 'Organicos'), ('Residuos_Peligrosos', 'Residuos_Peligrosos'), ('Aluminio', 'Aluminio')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='id_archivo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
