# Generated by Django 4.0.6 on 2022-10-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_usuario_total_puntos_alter_etiqueta_bottle_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiqueta',
            name='caneca',
        ),
    ]
