# Generated by Django 4.0.6 on 2022-10-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_remove_etiqueta_caneca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivo', models.CharField(max_length=150, null=True)),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True)),
                ('Usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usuario')),
            ],
        ),
    ]
