# Generated by Django 4.0.6 on 2022-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
