# Generated by Django 4.0.6 on 2022-11-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=45)),
                ('costo', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
