# Generated by Django 4.0.6 on 2022-11-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='_', max_length=1000),
            preserve_default=False,
        ),
    ]
