# Generated by Django 4.0.6 on 2022-11-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('etiquetado', 'etiquetado'), ('clasificado', 'clasificado'), ('canjeo', 'canjeo')], max_length=45),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='cantidad_puntos',
            field=models.IntegerField(default=0),
        ),
    ]
