# Generated by Django 4.0 on 2023-11-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(max_length=45, null=True)),
                ('package_color', models.CharField(max_length=45, null=True)),
                ('bottle_cap', models.CharField(max_length=45, null=True)),
                ('dirtiness', models.CharField(max_length=45, null=True)),
                ('packaging_type', models.CharField(max_length=45, null=True)),
                ('brand', models.CharField(max_length=45, null=True)),
                ('reference', models.CharField(max_length=45, null=True)),
                ('capacity', models.CharField(max_length=45, null=True)),
                ('damage', models.CharField(max_length=45, null=True)),
                ('custom_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('custom_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Clasification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('custom_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('etiquetado', 'etiquetado'), ('clasificado', 'clasificado'), ('canjeo', 'canjeo')], max_length=45)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('custom_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.customuser')),
            ],
        ),
    ]
