name: Docker Image CI

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types: [completed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --tag danielgara/ecomind:latest
      
    - name: Docker Push
      run: docker push danielgara/ecomind